### ISSUE TITLE
[main error] scan config 05: ERR: read timeout

### ISSUE THREAD

**Issue by HiQual** [danielkucera/esp8266-arduino-ebus#12]
Hello Daniel.
I have a ebusd question that I asked in the "discussions" section of ebusd 3 weeks ago but unfortunately no one has replied.
It might be that you have seen the error message and might give some information .....

https://github.com/john30/ebusd/discussions/743

Many thanks

**Comment by danielkucera** [comment]
I have no idea, but without full ebusd log I think nobody can figure out.
