### ISSUE TITLE
ESP8266 wifi LED

### ISSUE THREAD

**Issue by HiQual** [danielkucera/esp8266-arduino-ebus#2]
Hello Daniel.
Do the recent firmware changes turn off the bright blue wifi LED ?
If yes, I would like to upgrade my firmware again.
Last time we used method 2 (espota.py) which requires me to have a firmware.bin file.  Is there a simply way to download that?
Otherwise I will try method 1 (platform.io).
Many thanks ... Ian

**Comment by danielkucera** [comment]
Once a client connects, it will disable the TX-DISABLE pin (available in v3.0, so it can send to bus) and that LED is on the same pin. If you want it off, just cover it with a tape.

**Comment by HiQual** [comment]
Thanks for your very quick reply and explanation. I will follow your advice.
