### ISSUE TITLE
telnet connection

### ISSUE THREAD

**Issue by samezrp** [danielkucera/esp8266-arduino-ebus#21]
Hi,
I would like ask about telnet connection. According to info from description:

`to verify there are bytes being received by the adapter connect to esp-ebus.local TCP port using telnet - you should see unreadable binary data`

however when I try to read data I have putty info: connection refused.

When I run nmap it claims no 22 port open:
```
Starting Nmap 7.80 ( https://nmap.org ) at 2023-01-10 10:26 CET
Nmap scan report for esp-eBus (192.168.1.124)
Host is up (0.0064s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
3333/tcp open  dec-notes
5555/tcp open  freeciv
MAC Address: 40:22:D8:8B:C3:6D (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 8.16 seconds

```
Could you please confirm telnet port as opened?

**Comment by danielkucera** [comment]
Sorry for confusion, fixed in e5e6a82
Port 3334
