### ISSUE TITLE
UART programming fails, RXD pulled low by opamp

### ISSUE THREAD

**Issue by bakadave** [danielkucera/esp8266-arduino-ebus#27]
Hello!

If powered from the programming headers I could not transmit data to the MCU with an FT232 USB<->UART adapter due to RXD line being pulled low through R13. I haven't tried pulling TP1 up to 3V3 that might work in a pinch.

**Comment by danielkucera** [comment]
That's right, this is a small flaw but there are some USB-TTL adapters with strong pull which work. I have one chinese but it has no markings so I cannot tell you the exact type.

**Comment by bakadave** [comment]
Yep TP1 to 3V3 seemed to do the trick. (Although I am using 470R for R13 because that's the lowest I had.) May I suggest updating the Readme?
