### ISSUE TITLE
Is port 3335 both read and write?

### ISSUE THREAD

**Issue by HiQual** [danielkucera/esp8266-arduino-ebus#33]
Or should I be using port 3333 ?
I am using  SW release 5.0

**Comment by danielkucera** [comment]
yes

**Comment by danielkucera** [comment]
It was meant to be but I see your point now. It probably doesn't enable TX on older (pre 5.0) HW version.
I'll fix this soon.

**Comment by HiQual** [comment]
No hurry Daniel. I am away for the next 3 days.

**Comment by danielkucera** [comment]
Fixed in v5.2

**Comment by HiQual** [comment]
> 

Thanks, I will go to v5.3/firmware-HW_v3.x.bin
