### ISSUE TITLE
Unable to connect with espota.py

### ISSUE THREAD

**Issue by tomklapka** [danielkucera/esp8266-arduino-ebus#45]
HW: 5.1, UDP port 8266 seems unresponsive.

python3 espota.py -i 192.168.250.80 -f firmware-HW_v5.x.bin -r -d                                               
15:11:54 [DEBUG]: Options: {'esp_ip': '192.168.250.80', 'host_ip': '0.0.0.0', 'esp_port': 8266, 'host_port': 21351, 'auth': '', 'image': 'firmware-HW_v5.x.bin', 'spiffs': False, 'debug': True, 'progress': True}
15:11:54 [INFO]: Starting on 0.0.0.0:21351
15:11:54 [INFO]: Upload size: 918368
15:11:54 [INFO]: Sending invitation to: 192.168.250.80
15:12:04 [ERROR]: No Answer

**Comment by danielkucera** [comment]
Readme updated in #47
