### ISSUE TITLE
V2 board - recent updates

### ISSUE THREAD

**Issue by HiQual** [danielkucera/esp8266-arduino-ebus#9]
Hello Daniel.
Do the recent code updates apply to only the v3 boards?
Is there any reason to apply any of the recent updates to the V2 board?
Many thanks.

**Comment by danielkucera** [comment]
Hi,
there are some improvements (logging to serial1, reset using RX pin), feel free to update.

**Comment by HiQual** [comment]
I will do so.
Thanks for your reply.
